openapi: 3.0.3
info:
  title: Dojo-1 Service
  description: Dojo-1 HTTP service
  version: "1.0"
servers:
- url: http://localhost:3333
  description: hosts for Dojo-1 Service.
paths:
  /pais:
    post:
      tags:
      - pais
      summary: create_pais pais
      operationId: pais#create_pais
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaisRequestBody'
            example:
              nome: Culpa quod natus ex.
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaisDTO'
              example:
                id: Vero provident.
                nome: Eos ipsum aut tempora.
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /swagger.json:
    get:
      tags:
      - swagger
      summary: Download ../../gen/http/openapi.json
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    CreatePaisRequestBody:
      type: object
      properties:
        nome:
          type: string
          example: Necessitatibus dicta.
      example:
        nome: Autem vel repellat in ratione rerum ut.
      required:
      - nome
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    PaisDTO:
      type: object
      properties:
        id:
          type: string
          example: Alias nam ut impedit pariatur expedita quis.
        nome:
          type: string
          example: Dignissimos eos adipisci accusamus.
      example:
        id: Dolorem odit voluptatem vero harum velit quae.
        nome: Adipisci et reprehenderit vero.
      required:
      - id
      - nome
